; Base environments

[esp32]
extends = env
build_flags =
    ${env.build_flags}

[esp32c6]
extends = env
build_flags =
    ${env.build_flags}
; Use pioarduino, a community compatible fork of Platformio supporting latest espressif Arduino core
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[esp32c6-ota]
extends = esp32c6
upload_speed = 2000000
upload_protocol = espota
