[env]
lib_deps =
  SPI
  Wire
  I2C
  adafruit/Adafruit NeoPixel @ ^1.15.5
  mathertel/OneButton @ ^2.6.2
  sparkfun/SparkFun BME280 @ ^2.0.9
  lennarthennigs/ESP Telnet @ ^2.3.0

  ; extend libs for all platforms here
